require 'nfl/live_update/game_center/game'
require 'nfl/live_update/game_center/team'
require 'nfl/live_update/game_center/team_score'
require 'nfl/live_update/game_center/player_stat'
require 'nfl/live_update/game_center/team_stat'
